name: TaweeratItemStacker
version: '${project.version}'
main: com.taweerat.taweeratplugin.TaweeratItemStacker
api-version: '1.20'
commands:
  setradius:
    description: set stacker radius to specified value
    usage: /<command> <radius>
